> 学习使用Pytorch创建CNN网络

> 2022.05.12 kidzying

In [1]:
import torch
from torch import nn

In [2]:
linear = nn.Linear(32,2)

In [3]:
inputs = torch.rand(3,32)
outputs = linear(inputs)

In [4]:
print(outputs)

tensor([[ 0.0956, -0.5261],
        [-0.0708, -0.4145],
        [-0.0668, -0.2131]], grad_fn=<AddmmBackward0>)


In [5]:
inputs

tensor([[0.8802, 0.8769, 0.4235, 0.1109, 0.1475, 0.1654, 0.3668, 0.5460, 0.3983,
         0.6329, 0.5483, 0.5389, 0.1484, 0.2005, 0.2878, 0.9165, 0.1720, 0.0688,
         0.7665, 0.5246, 0.6454, 0.7416, 0.3530, 0.5818, 0.6466, 0.2234, 0.8878,
         0.8218, 0.1875, 0.8287, 0.0031, 0.6078],
        [0.1697, 0.6130, 0.2916, 0.0678, 0.8357, 0.8816, 0.5036, 0.8956, 0.9893,
         0.6749, 0.9234, 0.6510, 0.8525, 0.8853, 0.4945, 0.9099, 0.5758, 0.2033,
         0.6889, 0.6411, 0.6632, 0.7342, 0.6712, 0.8317, 0.1460, 0.3347, 0.3140,
         0.5581, 0.9888, 0.4312, 0.0053, 0.4697],
        [0.7664, 0.1642, 0.3281, 0.1771, 0.5606, 0.3597, 0.5221, 0.9429, 0.4006,
         0.2132, 0.7485, 0.4483, 0.8238, 0.3605, 0.1997, 0.5213, 0.6848, 0.9087,
         0.8223, 0.8838, 0.9130, 0.6805, 0.2496, 0.2090, 0.0896, 0.3182, 0.8176,
         0.5298, 0.4272, 0.4959, 0.9024, 0.8292]])

## 卷积神经网络CNN

### 一维卷积

In [6]:
import torch
from torch.nn import Conv1d

#### 构建网络

>一维卷积Conv1d的构造函数至少包括三个参数：in_channels输入通道，out_channels输出通道、对应卷积核的个数，kernel_size为每个卷积核的宽度

In [7]:
# 一维卷积，输入通道大小为5，输出通道大小为2，卷积核宽度为4
conv1 = Conv1d(5,2,4)
# 一维卷积，输入通道大小为5，输出通道大小为2，卷积核宽度为3
conv2 = Conv1d(5,2,3)

In [8]:
# 输入数据的形状为（batch，in_channels，seq_len)
inputs = torch.rand(2,5,6)
inputs

tensor([[[0.7001, 0.6645, 0.7429, 0.3448, 0.2897, 0.1736],
         [0.5868, 0.0724, 0.8808, 0.4649, 0.5535, 0.9587],
         [0.3212, 0.5075, 0.1694, 0.5022, 0.0561, 0.1603],
         [0.9489, 0.7473, 0.4341, 0.1113, 0.3758, 0.5996],
         [0.4055, 0.6466, 0.8264, 0.7796, 0.4680, 0.0603]],

        [[0.6665, 0.3454, 0.5944, 0.6981, 0.9614, 0.6788],
         [0.2939, 0.8204, 0.9914, 0.7654, 0.2428, 0.4744],
         [0.8561, 0.1077, 0.9316, 0.7863, 0.6753, 0.0523],
         [0.3043, 0.7616, 0.6850, 0.9666, 0.1929, 0.3616],
         [0.3737, 0.1974, 0.5354, 0.9284, 0.4352, 0.1611]]])

In [9]:
outputs1 = conv1(inputs)
outputs1

tensor([[[-0.1638, -0.0832, -0.3413],
         [ 0.0671, -0.0948,  0.1140]],

        [[-0.4938, -0.5925, -0.4118],
         [ 0.1571,  0.1913, -0.0564]]], grad_fn=<ConvolutionBackward0>)

In [10]:
outputs2 = conv2(inputs)
outputs2

tensor([[[0.4484, 0.4299, 0.3591, 0.2629],
         [0.1233, 0.1760, 0.1427, 0.2011]],

        [[0.3765, 0.4883, 0.4621, 0.2944],
         [0.2055, 0.2876, 0.2927, 0.1796]]], grad_fn=<ConvolutionBackward0>)

#### 增加池化层

##### 方式1：定义池化层对象

In [11]:
from torch.nn import MaxPool1d

In [12]:
pool1 = MaxPool1d(3)
pool3 = MaxPool1d(4)

In [13]:
outputs_pool1 = pool1(outputs1)
outputs_pool1

tensor([[[-0.0832],
         [ 0.1140]],

        [[-0.4118],
         [ 0.1913]]], grad_fn=<SqueezeBackward1>)

In [14]:
outputs_pool2 = pool1(outputs2)
outputs_pool2

tensor([[[0.4484],
         [0.1760]],

        [[0.4883],
         [0.2927]]], grad_fn=<SqueezeBackward1>)

##### 方式2：使用池化函数

In [15]:
import torch.nn.functional as F

In [16]:
outputs1.shape

torch.Size([2, 2, 3])

In [17]:
outputs_pool1 = F.max_pool1d(outputs1, kernel_size = outputs1.shape[2])
outputs_pool1

tensor([[[-0.0832],
         [ 0.1140]],

        [[-0.4118],
         [ 0.1913]]], grad_fn=<SqueezeBackward1>)

In [18]:
outputs_pool2 = F.max_pool1d(outputs2, kernel_size = outputs2.shape[2])
outputs_pool2

tensor([[[0.4484],
         [0.2011]],

        [[0.4883],
         [0.2927]]], grad_fn=<SqueezeBackward1>)

#### 合并池化层结果

In [19]:
outputs_pool1_squeeze = outputs_pool1.squeeze(dim=2)
outputs_pool1_squeeze

tensor([[-0.0832,  0.1140],
        [-0.4118,  0.1913]], grad_fn=<SqueezeBackward1>)

In [20]:
outputs_pool2_squeeze = outputs_pool2.squeeze(dim=2)
outputs_pool2_squeeze

tensor([[0.4484, 0.2011],
        [0.4883, 0.2927]], grad_fn=<SqueezeBackward1>)

In [21]:
outputs_pool = torch.cat([outputs_pool1_squeeze, outputs_pool2_squeeze], dim=1)
outputs_pool

tensor([[-0.0832,  0.1140,  0.4484,  0.2011],
        [-0.4118,  0.1913,  0.4883,  0.2927]], grad_fn=<CatBackward0>)

#### 增加全连接层

In [22]:
from torch.nn import Linear

In [23]:
linear = Linear(4, 2)
outputs_linear = linear(outputs_pool)
outputs_linear

tensor([[-0.1149, -0.6229],
        [-0.0604, -0.7021]], grad_fn=<AddmmBackward0>)